gui:
  icon: YAWMIcon.png
  size_x: 700
  size_y: 400
logger:
  level: 0
service:
  auto_close_on_launch: true
  profiles_folder: profiles
source_port:
  binary: F:\GZDoom\gzdoom.exe
  wads_folder: F:\GZDoom\WADs
